apiVersion: v1
kind: Service
metadata:
  name: golang-backend-service
spec:
  selector:
    app: golang-backend
    tier: backend
  type: NodePort
  ports:
  - protocol: TCP
    port: 30001
    targetPort: http