apiVersion: v1
kind: Service
metadata:
  name: frontend-angular-loadbalancer-service
  labels:
    app: frontend-angular
    tier: frontend
spec:
  selector:
    app: frontend-angular
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
